name: Upptime
on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check response times
        uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Generate status website
        uses: upptime/uptime-monitor@master
        with:
          command: site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Generate summary
        uses: upptime/uptime-monitor@master
        with:
          command: summary
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./site
          cname: status.mytribefamily.com
